# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cat import Cat
from swagger_server import util


class CatsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cats: List[Cat]=None):  # noqa: E501
        """CatsResponse - a model defined in Swagger

        :param cats: The cats of this CatsResponse.  # noqa: E501
        :type cats: List[Cat]
        """
        self.swagger_types = {
            'cats': List[Cat]
        }

        self.attribute_map = {
            'cats': 'cats'
        }

        self._cats = cats

    @classmethod
    def from_dict(cls, dikt) -> 'CatsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CatsResponse of this CatsResponse.  # noqa: E501
        :rtype: CatsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cats(self) -> List[Cat]:
        """Gets the cats of this CatsResponse.

        List of cats  # noqa: E501

        :return: The cats of this CatsResponse.
        :rtype: List[Cat]
        """
        return self._cats

    @cats.setter
    def cats(self, cats: List[Cat]):
        """Sets the cats of this CatsResponse.

        List of cats  # noqa: E501

        :param cats: The cats of this CatsResponse.
        :type cats: List[Cat]
        """

        self._cats = cats
